all:
	true

install:
	mkdir -p $(DESTDIR)/usr/lib/qubes
	cp cleanup-dispvms $(DESTDIR)/usr/lib/qubes
	cp startup-misc.sh $(DESTDIR)/usr/lib/qubes
	cp fix-dir-perms.sh $(DESTDIR)/usr/lib/qubes/
	cp write-qube-file.sh $(DESTDIR)/usr/lib/qubes
	cp start-guids.sh $(DESTDIR)/usr/lib/qubes
